<?php
/* Aqui estão as variáveis a receberem as informações do front
*/

$Nomedoprojeto = "204502";
$Segmento = "Exposição de artes visuais";
$Área = "Artes visuais";
$Mecanismo = "Mecenato";
$Enquadramento = "Artigo 18";
$Município_UF = "João Pessoa, PB";
$Anodoprojeto = "2020";
$Datatérmino = "31/12/2023";
$Datainício = "03/02/2021";
$Situação = "Autorizado a captação residual dos recursos";
$Valordaproposta = "R$ 207.299,84";
$Valoraprovado = "R$ 207.299,84";
$Valorcaptado = "R$ 250,00";
$Valorprojeto = "R$ 207.299,84";
$Proponente = "PARAHYBOLICA AGENCIA E PRODUCAO CULTURAL EIRELI - ME";
?>